-- Radar de Mercado: tablas privadas, una fila pertenece a una sola cuenta.
-- Ejecuta todo este archivo en Supabase SQL Editor antes de habilitar registros.

create table if not exists public.settings (
    user_id uuid not null references auth.users(id) on delete cascade,
    key text not null,
    value text not null,
    primary key (user_id, key)
);

create table if not exists public.source_status (
    user_id uuid not null references auth.users(id) on delete cascade,
    source text not null,
    state text not null,
    message text not null,
    last_attempt timestamptz,
    last_success timestamptz,
    primary key (user_id, source)
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    category text not null default '',
    country text not null default '',
    currency text not null default 'EUR',
    provider text not null default '',
    provider_url text not null default '',
    source_url text not null default '',
    product_cost double precision not null default 0,
    shipping_cost double precision not null default 0,
    ad_cost double precision not null default 0,
    platform_fee_pct double precision not null default 0,
    tax_pct double precision not null default 0,
    refund_pct double precision not null default 0,
    sale_price double precision not null default 0,
    launch_budget double precision not null default 0,
    delivery_days integer,
    supplier_quality double precision,
    demand_score double precision,
    demand_source text not null default '',
    demand_updated text not null default '',
    competition_score double precision,
    competitor_price double precision,
    competition_source text not null default '',
    fragile smallint not null default 0 check (fragile in (0, 1)),
    return_risk smallint not null default 0 check (return_risk in (0, 1)),
    legal_risk smallint not null default 0 check (legal_risk in (0, 1)),
    brand_risk smallint not null default 0 check (brand_risk in (0, 1)),
    notes text not null default '',
    is_favorite smallint not null default 0 check (is_favorite in (0, 1)),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    unique (id, user_id)
);

create table if not exists public.watchlist (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    asset_type text not null,
    name text not null default '',
    currency text not null default '',
    created_at timestamptz not null,
    unique (user_id, symbol, asset_type)
);

create table if not exists public.asset_observations (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    asset_type text not null,
    name text not null default '',
    price double precision not null,
    currency text not null default '',
    change_pct double precision,
    volume double precision,
    market_cap double precision,
    volatility_pct double precision,
    avg_volume double precision,
    avg_value double precision,
    source text not null,
    source_url text not null default '',
    as_of text not null default '',
    fetched_at timestamptz not null,
    details text not null default '{}'
);

create table if not exists public.product_observations (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    product_id bigint not null,
    sale_price double precision not null,
    demand_score double precision,
    competition_score double precision,
    competitor_price double precision,
    product_cost double precision not null default 0,
    shipping_cost double precision not null default 0,
    margin_pct double precision,
    observed_at timestamptz not null,
    foreign key (product_id, user_id) references public.products(id, user_id) on delete cascade
);

create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    kind text not null,
    target text not null,
    operator text not null,
    threshold double precision not null,
    label text not null default '',
    active boolean not null default true,
    status text not null default 'pendiente',
    created_at timestamptz not null,
    triggered_at timestamptz,
    last_checked timestamptz,
    details text not null default ''
);

create table if not exists public.portfolios (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    currency text not null,
    initial_cash double precision not null,
    created_at timestamptz not null,
    unique (id, user_id)
);

create table if not exists public.sim_trades (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    portfolio_id bigint not null,
    symbol text not null,
    asset_type text not null,
    action text not null,
    quantity double precision not null,
    price double precision not null,
    fee double precision not null default 0,
    created_at timestamptz not null,
    foreign key (portfolio_id, user_id) references public.portfolios(id, user_id) on delete cascade
);

create table if not exists public.portfolio_marks (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    portfolio_id bigint not null,
    cash double precision not null,
    market_value double precision not null,
    total_value double precision not null,
    benchmark_symbol text not null default '',
    benchmark_price double precision,
    valuation_source text not null default 'manual',
    details text not null default '',
    created_at timestamptz not null,
    foreign key (portfolio_id, user_id) references public.portfolios(id, user_id) on delete cascade
);

create table if not exists public.lesson_progress (
    user_id uuid not null references auth.users(id) on delete cascade,
    lesson_id text not null,
    completed boolean not null default false,
    quiz_score double precision,
    updated_at timestamptz not null,
    primary key (user_id, lesson_id)
);

create table if not exists public.image_analyses (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    mode text not null check (mode in ('Dropshipping', 'Trading')),
    file_name text not null,
    analysis text not null default '',
    status text not null default 'procesando' check (status in ('procesando', 'completado', 'error')),
    created_at timestamptz not null
);

-- Row Level Security protege también ante una consulta mal filtrada en la aplicación.
do $$
declare target_table text;
        sequence_name text;
begin
    foreach target_table in array array[
        'settings', 'source_status', 'products', 'watchlist', 'asset_observations',
        'product_observations', 'alerts', 'portfolios', 'sim_trades',
        'portfolio_marks', 'lesson_progress', 'image_analyses'
    ] loop
        execute format('alter table public.%I enable row level security', target_table);
        execute format('revoke all on table public.%I from anon, public', target_table);
        execute format('grant select, insert, update, delete on table public.%I to authenticated', target_table);
        execute format('drop policy if exists user_owns_rows on public.%I', target_table);
        execute format(
            'create policy user_owns_rows on public.%I for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',
            target_table
        );
        if exists (
            select 1
            from information_schema.columns c
            where c.table_schema = 'public'
              and c.table_name = target_table
              and c.column_name = 'id'
        ) then
            sequence_name := pg_get_serial_sequence(format('public.%I', target_table), 'id');
            if sequence_name is not null then
                execute format('grant usage, select on sequence %s to authenticated', sequence_name);
            end if;
        end if;
    end loop;
end $$;

grant usage on schema public to authenticated;

create index if not exists products_owner_created_idx on public.products(user_id, created_at desc);
create index if not exists observations_owner_symbol_idx on public.asset_observations(user_id, symbol, asset_type, fetched_at desc);
create index if not exists product_observations_owner_product_idx on public.product_observations(user_id, product_id, observed_at);
create index if not exists alerts_owner_created_idx on public.alerts(user_id, created_at desc);
create index if not exists image_analyses_owner_created_idx on public.image_analyses(user_id, created_at desc);
